# Site settings
title: Presentation Page
email: kharma@gmail.com
description: "Presentation Page for Kharma"
baseurl: ""
url: "http://walteryu.com"
twitter_username: walteryu
github_username:  kharma

# Build settings
markdown: kramdown
permalink: pretty
